name: ymlenv
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - python=3.8.8
  - opencv=4.0.1
  - pandas=1.2.4
  - matplotlib=3.3.4
  - scipy=1.6.2
  - pip=21.0.1
  - pip:
    - python-bioformats==4.0.4