name: Automated build

# Run this job on pushes to Github, on manual dispatch, and on schedule
on: 
  push:
  workflow_dispatch:
  schedule:
    - cron: '30 12 * * 5'  # 12:30 pm every Friday

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Compile thesis
        run: |
          docker build -t wduverger/msc-thesis -f ./Dockerfile.python .
          docker run -v ${{ github.workspace }}:/workspace wduverger/msc-thesis

          docker build -t wduverger/latex -f ./Dockerfile.latex .
          docker run -v ${{ github.workspace }}:/workspace wduverger/latex

      - name: Save thesis
        uses: actions/upload-artifact@v2
        with:
          name: thesis
          path: ./*.pdf

      # If running on master branch, publish container image to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          username: wduverger
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Publish docker image
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          TAG="${{ github.sha }}-$(date +%Y.%m.%d-%H.%M)"
          docker push wduverger/msc-thesis
          docker tag  wduverger/msc-thesis wduverger/msc-thesis:$TAG
          docker push wduverger/msc-thesis:$TAG