name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      TEXLIVE_DIGEST: 27d45ccba7a4d49dd3397f914f06218cb7aeffe8b2d1f78e8ccd2ebdee1adfd2

    steps:      
    
      - name: Initialise Docker cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: wduverger
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Find docker cache location
        run: docker info

      - name: Build python container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags:  wduverger/msc-thesis:${{ github.sha }}
          push: false

      - name: Pull latex container
        run: docker pull texlive/texlive

      - name: Compile figures
        uses: addnab/docker-run-action@v3
        with:
          image: wduverger/msc-thesis:${{ github.sha }}
          options: -v ${{ github.workspace }}:/workspace
          run: make -j8 figures

      - name: Compile thesis
        uses: addnab/docker-run-action@v3
        with:
          image: texlive/texlive:$TEXLIVE_DIGEST
          options: -v ${{ github.workspace }}:/workspace
          run: |
            cd workspace
            make thesis

      - name: Save thesis
        uses: actions/upload-artifact@v2
        with:
          name: thesis-web
          path: ./*.pdf      
          
      # If running on master branch, publish container to Docker Hub    
      - name: Publish python container
        id: docker_publish
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags:  wduverger/msc-thesis:${{ github.sha }}
          push: true
