name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:      
    
    - name: Initialise Docker cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: wduverger
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build python container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags:  wduverger/msc-thesis:latest
          push: false

      - name: Pull latex container
        run: docker pull texlive/texlive

      - name: Compile figures
        run: docker run -v ${PWD}:/workspace wduverger/msc-thesis make -j8 figures

      - name: Compile thesis
        run: docker run -v ${PWD}:/workspace texlive/texlive bash -c "cd workspace && make thesis"

      # - name: Push container to DockerHub
      #   run: push wduverger/msc-thesis
      #   env: 
      #     DOCKER_SECRETS

      - name: Publish python container
        id: docker_publish
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags:  wduverger/msc-thesis:latest
          push: false

      - name: Save thesis
        uses: actions/upload-artifact@v2
        with:
          name: thesis-web
          path: ./*.pdf