name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 12 * * *'  # Run at 12:30 pm every day

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Define docker tag
        id: docker-tag
        run: |
          echo "image_name=wduverger/msc-thesis" >> $GITHUB_ENV
          echo "image_tagged=wduverger/msc-thesis:${{ github.sha }}-$(date +%Y.%m.%d-%H.%M)" >> $GITHUB_ENV
          echo "image_tagged=wduverger/msc-thesis:${{ github.sha }}-$(date +%Y.%m.%d-%H.%M)"

      - name: Build python container
        run: docker build -t ${{ env.image_name }} .

      - name: Compile figures
        run: |
          docker run \
            -v ${{ github.workspace }}:/workspace \
            ${{ env.image_name }} \
            make -j8 figures

      - name: Compile thesis
        run: |
          docker pull texlive/texlive
          docker run \
            -v ${{ github.workspace }}:/workspace \
            texlive/texlive \
            bash -c "cd workspace && make thesis"

      - name: Save thesis
        uses: actions/upload-artifact@v2
        with:
          name: thesis
          path: ./*.pdf      

      # If running on master branch, publish container to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Publish docker image
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          docker push ${{ env.image_name   }}
          docker tag  ${{ env.image_name   }} ${{ env.image_tagged }}
          docker push ${{ env.image_tagged }}
          