name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:      
    
      # - name: Initialise Docker cache
      #   uses: actions/cache@v2
      #   with:
      #     path: /var/lib/docker
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build python container
        run: |
          export TAG="wduverger/msc-thesis:${{ github.sha }}-$(date +%s)"
          docker build -t $TAG .

      - name: Pull latex container
        run: docker pull texlive/texlive

      - name: Compile figures
        run: |
          docker run -v ${{ github.workspace }}:/workspace $TAG \
            make -j8 figures

      - name: Compile thesis
        run: |
          docker run -v ${{ github.workspace }}:/workspace \
            texlive/texlive \
            bash -c "cd workspace && make thesis"

      - name: Save thesis
        uses: actions/upload-artifact@v2
        with:
          name: thesis-web
          path: ./*.pdf      

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # If running on master branch, publish container to Docker Hub
      - name: Publish docker image
        if: ${{ github.ref == 'refs/heads/master' }}
        run: docker push $TAG
          