name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build python container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: wduverger/msc-thesis:latest

      - name: Pull latex container
        run: docker pull texlive/texlive

      - name: Compile figures
        run: docker run -v ${PWD}:/workspace wduverger/msc-thesis make -j8 figures

      - name: Compile thesis
        run: docker run -v ${PWD}:/workspace texlive/texlive bash -c "cd workspace && make thesis"

      # - name: Push container to DockerHub
      #   run: push wduverger/msc-thesis
      #   env: 
      #     DOCKER_SECRETS

      - name: Save thesis (web)
        uses: actions/upload-artifact@v2
        with:
          name: thesis-web
          path: './MSc thesis Wouter Duverger.pdf'

      - name: Save thesis (print)
        uses: actions/upload-artifact@v2
        with:
          name: thesis-print
          path: './MSc thesis Wouter Duverger (print).pdf'
