# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: 
  push:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile report
        run: |
          ls -la figures_generated/
          sudo touch figures_generated/testsudo
          touch figures_generated/test
          ls -la figures_generated/

          docker pull wduverger/msc-thesis
          docker run --rm -v ${PWD}:/workspace wduverger/msc-thesis ls -la
          ls -la figures_generated/
          # docker run --rm -v ${PWD}:/workspace texlive/texlive bash -c "cd workspace && make report"
          # ls -la
